import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod";
import { GeminiModel, MistralModel, CohoreModel } from "./Models.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";
import { TavilyService } from "./internetService.js";

const state = new StateSchema({
    problem: z.string().default(""),
    web_context: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

function shouldSearch(query: string) {
    console.log("Should search Running")
    return /latest|news|2025|2026|current|today|now/i.test(query);
}


const solutionNode: GraphNode<typeof state> = async (state) => {

    let web = { answer: "", context: [], sources: [] };

    // console.log(shouldSearch(state.problem))
    //  if (shouldSearch(state.problem)) {
        // }
            web = await TavilyService(state.problem);
    
    const prompt = `
Question: ${state.problem}

Web Answer:
${web.answer}

Extra Context:
${web.context.join("\n")}
`;
    const [mistralResponse, cohereResponse] = await Promise.all([
        MistralModel.invoke(prompt),
        CohoreModel.invoke(prompt)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const judge = createAgent({
        model: GeminiModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    })

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }

}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) {

    const result = await graph.invoke({
        problem: problem
    })

    return result;

}